### PR TITLE
#35 fix msvc compilation: server deps must also have static runtime

### PR DESCRIPTION
**Pull request by maximyurchuk**
The problem was in difference in runtime in sqlite libs (dynamic runtime) and zcatch server (static runtime).

### CODE REVIEW

**Comment by jxsl13** [comment]
:0

**Comment by jxsl13** [comment]
Man, that's awesome :0

**Comment by maximyurchuk** [comment]
Finally its works! 

Also PR build was completely broken, I have tried to fix it. Just a list of fixes:
- disabled "treat warning as errors" behaviour because 
	- Its not working with some 3rd party libraries (sqlite3). I've tried do use `-Wno-error` for such libraries, but another problem arises (see below)
	- on osx-latest there are some deprecates on objective-c code. No idea how to fix that (maybe not use latest image of osx)
- disable building of a client (because there are compilation errors). Maybe need some sync from original teeworlds repo
- switched from ubuntu 16.04 to 18.04 because modern cmake is needed (3.10 version)
- there is no dmg file for the builds without client on osx, so i've replaced that with simple ".tar.gz"

**Comment by jxsl13** [comment]
I don't build the client anyway.
The build.yaml from the main repo did not work, that's why I had the other three files there (had them before the teeworlds repo switched to github actions). when merging I just kept the files from the origin repo.

**Comment by jxsl13** [comment]
Giant thanks!

**Pull request merged**
